### ISSUE TITLE
AWS4 does not support query string as parameters in the passed options when used with the request npm module

### ISSUE THREAD

**Issue by e-nouri** [mhart/aws4#11]
I passed the query string 'qs' in the options then i signed my request for the API Gateway, but it still fails, turns out that aws4.sign(opts) does not take into account the opts.qs parameter for the querystring, so i had to compile the opts.path and opts.url if i want to add a query string before signing the request:

```javascript
    // add the query string to the path name and the url
    query = {"p1": v1, "p2": v2};

    opts.path = opts.path + '?' + qs.stringify(query);

    opts.url =  urlParse.format({
      host: host,
      protocol: protocol,
      pathname:  opts.path,
      query: query
    });

    // Sign the new request
    AWS4.sign(opts, {
      accessKeyId: configuration.accessKeyId,
      secretAccessKey: configuration.secretAccessKey
    });

    return rb.get(opts)
```

**Comment by mhart** [comment]
You're correct that the query string needs to be part of the `path` string.

I'm not sure what this `qs` option is that you're referring to?

**Comment by e-nouri** [comment]
`qs` is an option in request library for query string dictionary, I am using aws4 with request ...

**Comment by mhart** [comment]
Ah, ok – this library is for use with the [Node.js http module](https://nodejs.org/docs/latest/api/http.html#http_http_request_options_callback).

The [request npm module](https://github.com/request/request) is another module, written by other developers, that has been built on top of the Node.js http module.

**Comment by e-nouri** [comment]
Yes I figured that out after reading the examples and the doc, it would be very useful to add support to request, request makes the use of node http and https easier.

**Comment by mhart** [comment]
Thanks for the suggestion! I'm going to close this because the project's aim is to be a `small utility to sign vanilla node.js http(s) request options` – adding support for 3rd party modules doesn't really fit in with this aim.

I'm surprised that the request module *requires* the `uri`/`url` parameter and doesn't accept the same options as the Node.js module. If it accepted the standard `hostname` and `path` options, then you wouldn't need to create the uri/url yourself.
