### ISSUE TITLE
Invalid signature with secrets containing forward slash character

### ISSUE THREAD

**Issue by zanona** [mhart/aws4#22]
Today I have tried to perform a few requests using a generated secret key like: `/zsAn5edKuCsCEwhTyASPuk8RoT5DMukpbcvBB+Z` and unfortunately the signatures were failing which then could be fixed when generating a new key without the forward slash in the beginning.

I am not completely sure this was an issue with this library but thought it could be important to mention it here.

Thanks for the great tool.

**Comment by mhart** [comment]
Sorry for the delay – I finally got around to testing this by generating a secret key that begins with a slash (`/aj3lQhkSp4BRwTeUH4AZHZ29bHAOz9n+uwpWglM`) and it worked fine with `aws4`.

So I suspect the problem must have been in your code somewhere – either they way you were supplying or storing the secret key.

Unfortunately AWS gives the same error message for when the secret key is incorrect (ie, you've chopped off a character or mangled it somehow) – as for whether the signing was performed correctly or not (which is why it says "Check your AWS Secret Access Key and signing method"). It would be useful if they gave a different error message for each case, but they may have decided that reveals too much information from a security standpoint.

**Comment by zanona** [comment]
Thanks a lot for taking the time to test it @mhart and apologies for the false alarm.
