### ISSUE TITLE
Support for content-type: multipart/form-data

### ISSUE THREAD

**Issue by vvavepacket** [mhart/aws4#61]
I see that the body must be string/JSON/text/etc, what if the body is actually a multipart/form-data? How can we pass it on this plugin so it can be calculated as part of signature?

**Comment by mhart** [comment]
The body can be a string or a binary Buffer. You just need to set the `Content-Type` header to whatever content type your body is.

**Comment by makanti** [comment]
Hello there,
I have been struggling with this quite a lot. Uploading file fails when I try to switch the API calls to signed ones. I am posting a formData object using content-type 'multipart/form-data' but I still get a mismatch.
I am using axios for the POST request and including data and body both in formData format. 
All the rest of the GET/PUT/POST requests work well apart from when I try to upload the file.
Would the boundary set by the browser cause an issue on this?

**Comment by mhart** [comment]
I'm not sure what a `formData` object is – is it something axios specific?

If you can get the body into a plain text string as [specified by the multipart/form-data RFC](https://tools.ietf.org/html/rfc2388), then `aws4` should be able to sign it correctly

**Comment by makanti** [comment]
Hi again @mhart. Thanks for your response. I tried a few different things but no luck.

I put together a demo to demonstrate the issue here:
In the demo, I removed the Axios from the stack. I am using vanilla javascript to make the Ajax file upload.
https://github.com/makanti/aws4-uploadfile-demo

components/App.jsx is where the request is setup (handleSubmit method is taking care of posting the request on form submition).
components/API.js is where you will find the method for signing the request (getSignedHTTPRequest) takes care of signing the request.

To answer your question, FormData is a javascript object which represents form fields and values. It is the way to send files via the XMLHttpRequest API.

Is there anything that I should be doing differently here? I can confirm that all the headers are matching correctly the ones in the expected canonical string, hence I am assuming the problem relies on the way the body is being encoded.

**Comment by mhart** [comment]
@makanti if you're using the browser's FormData API, then there's no way (that I know of) to get the raw body text, which is what you need to sign the request. You need to create the body manually.

Are you sure you need `multipart/form-data` for your API? It would be easier to just use `application/json` or similar if you have the option.

If it does have to be `multipart/form-data`, then you'll need to create a body like this:

```js
var headers = {
  'Content-Type': 'multipart/form-data; boundary=SomeBoundary123'
}

var body = `
--SomeBoundary123
Content-Disposition: form-data; name="file"; filename="file1.txt"
Content-Type: text/plain

... contents of file1.txt ...
--SomeBoundary123--
`

// do signing...
```

There are a number of references on the web if you want to do anything more complex, like multiple field values, base64 encoding, etc
