### ISSUE TITLE
Is this also compatible with minio?

### ISSUE THREAD

**Issue by thomaslange24** [mhart/aws4#89]
Can I also sign requests addressing a MinIO server with this module?

What i want to do is this: https://github.com/minio/minio/blob/master/docs/sts/assume-role.md 
in a Node.js application. But i am pretty new to this and do not know how to achieve it hte best way.

**Comment by solderjs** [comment]
The difference between `minio` and `aws` is that AWS uses REGION whereas minio uses Endpoint.

This will NOT work with Minio as-is, because it has the AWS Endpoint hard-coded.

If you fork this and change this line
https://github.com/mhart/aws4/blob/master/aws4.js#L85

```js
  return service + region + '.amazonaws.com'
```

to be like this:

```js
  return service + (endpoint ? endpoint : region + '.amazonaws.com')
```

A few other similar changes may be needed.

The minio s3 client has these changes already, and should work just as well with AWS:

* https://docs.min.io/docs/upload-files-from-browser-using-pre-signed-urls
* https://github.com/minio/minio-js/blob/master/src/main/signing.js

The official AWS client will also work with Minio as long as you specify Endpoint rather than Region.

**Comment by mhart** [comment]
You can also just specify host explicitly – as in the first example in the README

**Comment by solderjs** [comment]
doh

I was searching for “endpoint”. :-/
